image: node:latest
cache:
  paths: 
    - node_modules/ 
before_script:
  - npm install -g grunt-cli
pages:
  stage: deploy
  script:
    - rm -rf ./public
    - npm install
    - grunt default
    - mkdir public
    - rsync -av --progress . public --exclude public
    - ls ./public/
  artifacts:
    paths:
      - public 