image: node:latest
cache:
  paths: 
    - node_modules/ 
before_script:
  - npm install -g grunt-cli
pages:
  stage: deploy
  script:
    - npm install
    - grunt default
  artifacts:
    paths:
      - public 