image: node:latest
cache:
  paths: 
    - node_modules/ 
before_script:
  - npm install -g grunt-cli
pages:
  stage: deploy
  script:
    - npm install
    - grunt default
    - mkdir public
    - cp -rf ./* ./public/
    - ls ./public/
  artifacts:
    paths:
      - public 